export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';
export const LOAD_ALL_STUDENTS = 'LOAD_ALL_STUDENTS';
export const LOAD_ALL_STUDENTS_ERROR = 'LOAD_ALL_STUDENTS_ERROR';